# Generated by Django 5.1.1 on 2024-09-30 17:03

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id_commune', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DFP',
            fields=[
                ('id_dfp', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DRANEF',
            fields=[
                ('id_dranef', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('id_forest', models.AutoField(primary_key=True, serialize=False)),
                ('forest_name', models.CharField(max_length=255)),
                ('location_name', models.CharField(max_length=255)),
                ('surface_area', models.DecimalField(decimal_places=3, max_digits=7)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('num_canton', models.IntegerField(blank=True, null=True)),
                ('number_parcel', models.IntegerField(blank=True, null=True)),
                ('titre_foncier', models.CharField(blank=True, max_length=255, null=True)),
                ('forest_formation', models.CharField(choices=[('R', 'LES RESINEUSES'), ('F', 'LES FEUILLEUSES'), ('C', 'LES CEDRAIES'), ('S', 'LES SUBERAIES'), ('P', 'LES PINEDES')], default='F', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id_province', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id_groupe', models.AutoField(primary_key=True, serialize=False)),
                ('scientific_name', models.CharField(blank=True, max_length=255)),
                ('vernacular_name', models.CharField(blank=True, max_length=255, null=True)),
                ('french_name', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('species_importance', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DPANEF',
            fields=[
                ('id_dpanef', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dranef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gisportal.dranef')),
            ],
        ),
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id_canton', models.AutoField(primary_key=True, serialize=False)),
                ('canton_name', models.CharField(max_length=255)),
                ('surface_area', models.DecimalField(decimal_places=3, max_digits=6)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('num_groupe', models.IntegerField(blank=True, null=True)),
                ('forest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gisportal.forest')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id_groupe', models.AutoField(primary_key=True, serialize=False)),
                ('groupe_name', models.CharField(max_length=255, null=True)),
                ('surface_area', models.DecimalField(decimal_places=3, max_digits=6)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('parcel_number', models.IntegerField(blank=True, null=True)),
                ('canton', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gisportal.canton')),
                ('forest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gisportal.forest')),
            ],
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id_parcelle', models.AutoField(primary_key=True, serialize=False)),
                ('parcelle_name', models.CharField(max_length=255)),
                ('surface_area', models.DecimalField(decimal_places=3, max_digits=6)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gisportal.commune')),
                ('dfp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gisportal.dfp')),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gisportal.groupe')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gisportal.province'),
        ),
        migrations.AddField(
            model_name='province',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gisportal.region'),
        ),
        migrations.CreateModel(
            name='ParcelSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_species', models.IntegerField()),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gisportal.parcelle')),
                ('scientific_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gisportal.species')),
            ],
        ),
        migrations.CreateModel(
            name='ZDTF',
            fields=[
                ('id_zdtf', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dpanef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gisportal.dpanef')),
            ],
        ),
        migrations.AddField(
            model_name='dfp',
            name='zdtf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gisportal.zdtf'),
        ),
    ]
