# Generated by Django 5.1.1 on 2025-01-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gisportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groupe',
            table=None,
        ),
    ]
