# Generated by Django 5.1.3 on 2024-11-11 15:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gisportal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='id_groupe',
            new_name='id_species',
        ),
        migrations.AddField(
            model_name='parcelle',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
