# Generated by Django 5.1.3 on 2024-11-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisportal', '0002_rename_id_groupe_species_id_species_parcelle_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointCloudMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(unique=True)),
                ('species', models.CharField(blank=True, max_length=225, null=True)),
                ('height', models.FloatField()),
                ('circuference', models.FloatField()),
                ('more_fields', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
