# Generated by Django 5.1.3 on 2024-11-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisportal', '0003_pointcloudmetadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointcloudmetadata',
            name='id',
        ),
        migrations.AlterField(
            model_name='pointcloudmetadata',
            name='object_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
