# Generated by Django 5.1.3 on 2024-11-21 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gisportal', '0004_remove_pointcloudmetadata_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='geom',
        ),
    ]
