# Generated by Django 5.1.3 on 2024-12-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisportal', '0007_rename_espece_inventaire_especeinventaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especeinventaire',
            old_name='num_total',
            new_name='num_total_arbre',
        ),
        migrations.AddField(
            model_name='parcelspecies',
            name='num_total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcelspecies',
            name='volume_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
    ]
