# Generated by Django 5.1.3 on 2024-12-30 15:48

import datetime
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisportal', '0009_especeinventaire_volume_total_arbre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canton',
            old_name='num_groupe',
            new_name='number_groupe',
        ),
        migrations.RenameField(
            model_name='forest',
            old_name='num_canton',
            new_name='number_canton',
        ),
        migrations.RemoveField(
            model_name='pointcloudmetadata',
            name='circuference',
        ),
        migrations.RemoveField(
            model_name='pointcloudmetadata',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pointcloudmetadata',
            name='height',
        ),
        migrations.RemoveField(
            model_name='pointcloudmetadata',
            name='more_fields',
        ),
        migrations.RemoveField(
            model_name='pointcloudmetadata',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='pointcloudmetadata',
            name='species',
        ),
        migrations.AddField(
            model_name='commune',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='pointcloudmetadata',
            name='collecteur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pointcloudmetadata',
            name='date_collection',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='pointcloudmetadata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointcloudmetadata',
            name='id_parcelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gisportal.parcelle'),
        ),
        migrations.AddField(
            model_name='pointcloudmetadata',
            name='threeD_modellink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='region',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='especeinventaire',
            name='circonference',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especeinventaire',
            name='hauteur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especeinventaire',
            name='id_parcelspecies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gisportal.parcelspecies'),
        ),
        migrations.AlterField(
            model_name='especeinventaire',
            name='num_total_arbre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especeinventaire',
            name='volume_total_arbre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forest',
            name='forest_formation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='forest',
            name='surface_area',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
