# Generated by Django 5.1.3 on 2024-12-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisportal', '0010_rename_num_groupe_canton_number_groupe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='surface_area',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
