# Generated by Django 5.1.3 on 2024-12-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisportal', '0011_alter_parcelle_surface_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canton',
            name='surface_area',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='surface_area',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='parcelspecies',
            name='volume_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
