# Generated by Django 5.1.1 on 2025-01-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisportal', '0012_alter_canton_surface_area_alter_groupe_surface_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forest',
            name='surface_area',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='parcelspecies',
            name='volume_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
