# Generated by Django 5.1.1 on 2025-01-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisportal', '0013_alter_forest_surface_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShapefileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shapefile', models.FileField(upload_to='shapefiles/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
