# Generated by Django 5.1.1 on 2025-01-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gisportal', '0002_alter_groupe_table'),
        ('gisportal', '0014_shapefileupload'),
    ]

    operations = [
    ]
