# Generated by Django 5.1.1 on 2025-01-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisportal', '0015_shp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shp',
        ),
        migrations.AddField(
            model_name='canton',
            name='properties',
            field=models.JSONField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='commune',
            name='properties',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='forest',
            name='properties',
            field=models.JSONField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='groupe',
            name='properties',
            field=models.JSONField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='properties',
            field=models.JSONField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='province',
            name='properties',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='shapefileupload',
            name='model_name',
            field=models.CharField(default='defaultModelName', help_text='Enter the target model name (e.g Parcelle).', max_length=255),
            preserve_default=False,
        ),
    ]
