# Generated by Django 5.1.1 on 2025-01-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gisportal', '0017_shp_delete_shapefileupload_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcelle',
            old_name='id_parcelle',
            new_name='id_parcel',
        ),
        migrations.RenameField(
            model_name='parcelle',
            old_name='parcelle_name',
            new_name='parcelle',
        ),
        migrations.RenameField(
            model_name='parcelle',
            old_name='surface_area',
            new_name='superficie',
        ),
    ]
