# Generated by Django 5.1.1 on 2025-01-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gisportal', '0018_rename_id_parcelle_parcelle_id_parcel_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groupe',
            table='Groupe',
        ),
    ]
