# Generated by Django 5.1.1 on 2025-01-16 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisportal', '0019_alter_groupe_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canton',
            name='properties',
        ),
        migrations.AddField(
            model_name='shp',
            name='keyy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gisportal.parcelle'),
        ),
    ]
