# Generated by Django 5.1.1 on 2025-01-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisportal', '0020_remove_canton_properties_shp_keyy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shp',
            name='keyy',
        ),
        migrations.AddField(
            model_name='shp',
            name='model_type',
            field=models.CharField(choices=[('parcelle', 'Parcelle'), ('canton', 'Canton'), ('groupe', 'Groupe')], default='parc', max_length=10),
            preserve_default=False,
        ),
    ]
