# Generated by Django 5.1.1 on 2025-01-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gisportal', '0015_merge_0002_alter_groupe_table_0014_shapefileupload'),
        ('gisportal', '0022_rename_number_groupe_canton_num_groupe_and_more'),
    ]

    operations = [
    ]
