# Generated by Django 5.1.1 on 2025-01-17 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisportal', '0023_merge_20250117_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shpss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('file', models.FileField(upload_to='%Y/%m/%d')),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.DeleteModel(
            name='Shp',
        ),
        migrations.AlterModelTable(
            name='parcelle',
            table=None,
        ),
    ]
