# Generated by Django 5.1.1 on 2025-01-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globeportal', '0002_rename_number_groupe_canton_num_groupe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forest',
            old_name='titre_fonci',
            new_name='titre_fonc',
        ),
    ]
