# Generated by Django 5.1.1 on 2025-01-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globeportal', '0003_rename_titre_fonci_forest_titre_fonc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forest',
            old_name='forest_name',
            new_name='forest_nam',
        ),
    ]
