# Generated by Django 5.1.1 on 2025-01-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globeportal', '0004_rename_forest_name_forest_forest_nam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canton',
            old_name='canton_name',
            new_name='canton_nam',
        ),
    ]
