# Generated by Django 5.1.1 on 2025-01-25 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globeportal', '0005_rename_canton_name_canton_canton_nam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canton',
            name='forest',
            field=models.ForeignKey(blank=True, db_column='forest_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='globeportal.forest'),
        ),
        migrations.RenameField(
            model_name='canton',
            old_name='forest',
            new_name='forest_id',
        ),
    ]
