# Generated by Django 5.1.1 on 2025-01-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globeportal', '0006_alter_canton_forest_rename_forest_canton_forest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='superficie',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='forest',
            name='superficie',
            field=models.DecimalField(db_column='superficie', decimal_places=3, max_digits=12),
        ),
    ]
