# Generated by Django 5.1.1 on 2025-01-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globeportal', '0007_commune_superficie_alter_forest_superficie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commune',
            old_name='province',
            new_name='province_id',
        ),
    ]
