# Generated by Django 5.1.1 on 2025-01-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globeportal', '0008_rename_province_commune_province_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='province_id',
            field=models.ForeignKey(db_column='province_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='globeportal.province'),
        ),
    ]
