# Generated by Django 5.1.1 on 2025-01-25 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globeportal', '0009_alter_commune_province_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commune',
            name='province_id',
        ),
        migrations.AddField(
            model_name='commune',
            name='province_i',
            field=models.ForeignKey(db_column='province_i', null=True, on_delete=django.db.models.deletion.CASCADE, to='globeportal.province'),
        ),
    ]
