# Generated by Django 5.1.1 on 2025-01-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globeportal', '0010_remove_commune_province_id_commune_province_i'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='superficie',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
