# Generated by Django 5.1.1 on 2025-01-27 09:48

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globeportal', '0013_rename_id_province_province_id_provinc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canton',
            name='canton_nam',
            field=models.CharField(db_column='canton_nam', max_length=255),
        ),
        migrations.AlterField(
            model_name='canton',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, db_column='geometry', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='canton',
            name='id_canton',
            field=models.AutoField(db_column='id_canton', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='canton',
            name='num_groupe',
            field=models.IntegerField(blank=True, db_column='num_groupe', null=True),
        ),
        migrations.AlterField(
            model_name='canton',
            name='superficie',
            field=models.DecimalField(db_column='superficie', decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='commune',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, db_column='geometry', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='commune',
            name='id_commune',
            field=models.AutoField(db_column='id_commune', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commune',
            name='name',
            field=models.CharField(db_column='name', max_length=255),
        ),
        migrations.AlterField(
            model_name='commune',
            name='superficie',
            field=models.DecimalField(blank=True, db_column='superficie', decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='dfp',
            name='id_dfp',
            field=models.AutoField(db_column='id_dfp', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dfp',
            name='name',
            field=models.CharField(db_column='name', max_length=255),
        ),
        migrations.AlterField(
            model_name='dfp',
            name='zdtf',
            field=models.ForeignKey(db_column='zdtf', null=True, on_delete=django.db.models.deletion.CASCADE, to='globeportal.zdtf'),
        ),
        migrations.AlterField(
            model_name='dpanef',
            name='dranef',
            field=models.ForeignKey(db_column='dranef', null=True, on_delete=django.db.models.deletion.CASCADE, to='globeportal.dranef'),
        ),
        migrations.AlterField(
            model_name='dpanef',
            name='id_dpanef',
            field=models.AutoField(db_column='id_dpanef', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpanef',
            name='name',
            field=models.CharField(db_column='name', max_length=255),
        ),
        migrations.AlterField(
            model_name='dranef',
            name='id_dranef',
            field=models.AutoField(db_column='id_dranef', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dranef',
            name='name',
            field=models.CharField(db_column='name', max_length=255),
        ),
        migrations.AlterField(
            model_name='forest',
            name='for_format',
            field=models.CharField(blank=True, db_column='for_format', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='forest',
            name='forest_nam',
            field=models.CharField(db_column='forest_nam', max_length=255),
        ),
        migrations.AlterField(
            model_name='forest',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, db_column='geometry', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='forest',
            name='id_forest',
            field=models.AutoField(db_column='id_forest', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='forest',
            name='loc_name',
            field=models.CharField(db_column='loc_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='forest',
            name='num_canton',
            field=models.IntegerField(blank=True, db_column='num_canton', null=True),
        ),
        migrations.AlterField(
            model_name='forest',
            name='num_parcel',
            field=models.IntegerField(blank=True, db_column='num_parcel', null=True),
        ),
        migrations.AlterField(
            model_name='forest',
            name='titre_fonc',
            field=models.CharField(blank=True, db_column='titre_fonc', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='canton',
            field=models.ForeignKey(blank=True, db_column='canton', null=True, on_delete=django.db.models.deletion.CASCADE, to='globeportal.canton'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='forest',
            field=models.ForeignKey(blank=True, db_column='forest', null=True, on_delete=django.db.models.deletion.CASCADE, to='globeportal.forest'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, db_column='geometry', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='groupe_name',
            field=models.CharField(db_column='groupe_name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='id_groupe',
            field=models.AutoField(db_column='id_groupe', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='parcel_num',
            field=models.IntegerField(blank=True, db_column='parcel_num', null=True),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='superficie',
            field=models.DecimalField(db_column='superficie', decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='province',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, db_column='geometry', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='province',
            name='id_provinc',
            field=models.AutoField(db_column='id_provinc', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(db_column='name', max_length=255),
        ),
        migrations.AlterField(
            model_name='province',
            name='region',
            field=models.ForeignKey(db_column='region', null=True, on_delete=django.db.models.deletion.CASCADE, to='globeportal.region'),
        ),
        migrations.AlterField(
            model_name='province',
            name='superficie',
            field=models.DecimalField(blank=True, db_column='superficie', decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, db_column='geometry', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='region',
            name='id_region',
            field=models.AutoField(db_column='id_region', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(db_column='name', max_length=255),
        ),
        migrations.AlterField(
            model_name='region',
            name='superficie',
            field=models.DecimalField(blank=True, db_column='superficie', decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='zdtf',
            name='dpanef',
            field=models.ForeignKey(db_column='dpanef', null=True, on_delete=django.db.models.deletion.CASCADE, to='globeportal.dpanef'),
        ),
        migrations.AlterField(
            model_name='zdtf',
            name='id_zdtf',
            field=models.AutoField(db_column='id_zdtf', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='zdtf',
            name='name',
            field=models.CharField(db_column='name', max_length=255),
        ),
    ]
